{% set version = "2.3.11" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-yaml
  version: {{ version|replace("-", "_") }}

source:
  fn: yaml_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/yaml_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/yaml/yaml_{{ version }}.tar.gz
  sha256: b9c4fa70b9e2ba2257d59b7d4ba5d80106ed63f66d6d2a4da26b754160bac22c

build:
  number: 0
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - cross-r-base {{ r_base }}  # [build_platform != target_platform]
    - {{ compiler('c') }}        # [not win]
    - {{ stdlib("c") }}          # [not win]
    - {{ compiler('m2w64_c') }}  # [win]
    - {{ stdlib("m2w64_c") }}    # [win]
    - {{ posix }}filesystem      # [win]
    - {{ posix }}make
    - {{ posix }}sed             # [win]
    - {{ posix }}coreutils       # [win]
    - {{ posix }}zip             # [win]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('yaml')"           # [not win]
    - "\"%R%\" -e \"library('yaml')\""  # [win]

about:
  home: https://github.com/viking/r-yaml/
  license: BSD-3-Clause
  license_file:
    - LICENSE
    - COPYING

  summary: Implements the 'libyaml' 'YAML' 1.1 parser and emitter (<http://pyyaml.org/wiki/LibYAML>) for R.
  license_family: BSD

extra:
  recipe-maintainers:
    - conda-forge/r
    - croth1
    - bsennblad
