appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: gZCu64NRISlHb3cHUWgSgyg+VeTjHGGoNk3Qtt+/d2k48vnF6xaCVVC7h83Q6LO5Zea7XcRPdZXX/VITXac8KNHuBtm9nBdrexzPtssmI6lmZMzrew323+hxvreANE5I9PsE1Cxv/jyYOZtzoiWrMijSDAvWCsMdX/NIbJ5Ab7cjzoJVzDvxWVXRzCqP8CQYyOVCdTZPtBD+r5fh4OjGsIk34bGT6hsiXSbkjXeBld9cparjMgl45j4lO5mXML1f/AstYf2Cl9VIFyl1iShDhMD0Gb6/UAmSL72gPNdRN9hVgv59j/ATfyaqU4MolsC3Ot6/XtWtdG8IArm5FBsgI2cREcDkQhcIVR6cB8uQG2lGlFGJ0WGUObklf581CNTgHNiTtK5ZWH/B3xQ5kXELCChX0WbM3vqJu220abXY8m3QQ4fdOVPbrwOnj/IwfPdALokIOAMDM3DLvFoC3/mgJS6Mcu+DQPD1YQeosenILr4apCok2hzxnznMgybqp8d2N/XH+OCfnwhIyQGKFC9JuUefUY0alswJHo7IjIllh6YHo9sDDoKWEzm3990OJDwEAdMHJszMpCuCJJ0GtZrXxEkLMD9aO2As1Nn5wBgMmPynWijzeEJ+kAFHEmdfJEcXJ4ThzKmJR6mep+V521XJADXGTPA8/u1Hm8YHw/F7ur0=}
